# Generated by Django 4.2.7 on 2023-12-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_alter_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(upload_to='car/media/uploads/'),
        ),
    ]
